import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Tactic

open MvPolynomial

/-!
# Weyl Algebras and the Dixmier Conjecture — honest version

STATUS: unverified. Not yet run through `lake build`. Written to replace the
previous placeholder (`WeylAlgebra n := Unit`, `DixmierConjecture n := True`),
which asserted nothing. This file is an attempt at a mathematically faithful
definition; every lemma below with no proof is left as `sorry`, explicitly.

Construction. Rather than presenting A_n abstractly by generators and
relations, we use its defining representation: A_n IS the ring of
differential operators with polynomial coefficients acting on ℚ[x_1,...,xn].
This action is faithful in characteristic 0 (a standard fact), so this is not
a model or an analogy — it is the Weyl algebra itself, realized concretely.
-/

variable (n : ℕ)

/-- "Multiplication by xᵢ" as a linear endomorphism of the polynomial ring. -/
noncomputable def mulX (i : Fin n) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ where
  toFun p := X i * p
  map_add' p q := by ring
  map_smul' c p := by simp [mul_smul_comm]

/-- The n-th Weyl algebra, realized concretely as the subalgebra of
`End ℚ (MvPolynomial (Fin n) ℚ)` generated by all multiplication-by-xᵢ
operators together with all pderiv i operators.

This is the *standard representation* of A_n, not a placeholder: an
element of A_n is exactly a finite ℚ-linear combination of finite products
of these generators, which is exactly what "polynomial-coefficient
differential operator" means. -/
noncomputable def WeylAlgebra (n : ℕ) :
    Subalgebra ℚ (MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :=
  Algebra.adjoin ℚ
    ((Set.range (fun i : Fin n => mulX n i)) ∪
     (Set.range (fun i : Fin n => (pderiv i : MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ))))

/-- The canonical commutation relation [∂ᵢ, xⱼ] = δᵢⱼ, the defining relation
of the Weyl algebra. Stated here as a sanity check that our concrete
`mulX`/`pderiv` generators actually satisfy the relation they're supposed to
— if this doesn't close by `simp`/`ring`-style automation once built, the
representation above is set up wrong and needs fixing before anything else
is trusted. -/
theorem pderiv_mulX_comm (i j : Fin n) (p : MvPolynomial (Fin n) ℚ) :
    pderiv i (mulX n j p) - mulX n j (pderiv i p) =
      (if i = j then 1 else 0) • p := by
  sorry -- expected: pderiv_mul, pderiv_X, then case split on i = j

/-- The Dixmier Conjecture in rank n, stated honestly: every ℚ-algebra
endomorphism of the Weyl algebra is bijective (hence an automorphism). -/
def DixmierConjecture (n : ℕ) : Prop :=
  ∀ φ : WeylAlgebra n →ₐ[ℚ] WeylAlgebra n, Function.Bijective φ

/-!
## What is still genuinely open (not attempted here)

The Secret Blogging Seminar argument (cited, not yet formalized) constructs,
from the Alpöge/Fable counterexample F = (F1, F2, F3), a *specific*
endomorphism φ_F of A_3 and shows it is not surjective. The real remaining
work, in order of difficulty:

1. Define the "dual derivations" ∂'ᵢ := Σⱼ (J⁻¹)ⱼᵢ ∂ⱼ, where J is the
   Jacobian matrix of F (this uses that det J = -2 is a unit, so J⁻¹ has
   polynomial entries — this is exactly why the argument needs the
   *constant* Jacobian hypothesis, not just non-vanishing).
2. Prove [∂'ᵢ, ∂'ⱼ] = 0 (the derivations still commute after the change of
   variables). This is the hardest, most novel lemma — it is NOT automatic
   from J being invertible alone; it depends on integrability specific to
   this construction and is the crux of why this argument is worth having
   as a Lean proof rather than prose.
2. Define φ_F : A_3 → A_3 by xᵢ ↦ Fᵢ, ∂ᵢ ↦ ∂'ᵢ, and prove it respects the
   defining relations (uses step 2 plus the chain rule ∂'ᵢ Fⱼ = δᵢⱼ).
3. Prove φ_F is not surjective: show the subring ℚ[F1, F2, F3] ⊊ ℚ[x, y, z].
   This follows from F not being a polynomial automorphism (already proved,
   `not_injective_despite_constant_jacobian` in `JacobianCounterexample.lean`)
   together with F being dominant (its Jacobian is everywhere nonzero) —
   dominant + non-injective implies the pullback on coordinate rings is
   injective but not surjective. This last implication (dominant ⟹ injective
   pullback, for this specific ring) is itself a real lemma to prove, not
   a one-liner.

None of steps 1–3 above are attempted in this file. `DixmierConjecture` above
is an honest statement of the target proposition; showing it is FALSE for
n = 3 (the actual goal) requires constructing φ_F and proving it is not
bijective, which is the real remaining task.
-/
