import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Tactic

open MvPolynomial

/-!
# Weyl Algebras and the Dixmier Conjecture — honest version

STATUS: unverified draft. Written to replace the previous placeholder
(`WeylAlgebra n := Unit`, `DixmierConjecture n := True`).
-/

variable (n : ℕ)

/-- "Multiplication by xᵢ" as a ℚ-linear endomorphism of MvPolynomial (Fin n) ℚ. -/
noncomputable def mulX (i : Fin n) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ where
  toFun p := X i * p
  map_add' p q := by ring
  map_smul' c p := by simp [mul_smul_comm]

/-- "Partial derivative ∂/∂xᵢ" bundled as a ℚ-linear endomorphism. -/
noncomputable def pderivLinear (i : Fin n) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ :=
  (pderiv i).toLinearMap

/-- The n-th Weyl algebra, realized concretely as the subalgebra of
`End ℚ (MvPolynomial (Fin n) ℚ)` generated by all multiplication-by-xᵢ
operators together with all partial derivative operators. -/
noncomputable def WeylAlgebra (n : ℕ) :
    Subalgebra ℚ (MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :=
  Algebra.adjoin ℚ
    ((Set.range (fun i : Fin n => mulX n i)) ∪
     (Set.range (fun i : Fin n => pderivLinear n i)))

/-- The canonical commutation relation [∂ᵢ, xⱼ] = δᵢⱼ • id. -/
theorem pderiv_mulX_comm (i j : Fin n) (p : MvPolynomial (Fin n) ℚ) :
    pderivLinear n i (mulX n j p) - mulX n j (pderivLinear n i p) =
    (if i = j then 1 else 0) • p := by
  sorry

/-- The Dixmier Conjecture in rank n: every ℚ-algebra endomorphism of A_n is bijective. -/
def DixmierConjecture (n : ℕ) : Prop :=
  ∀ φ : WeylAlgebra n →ₐ[ℚ] WeylAlgebra n, Function.Bijective φ
